version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      security-updates:
        applies-to: "security-updates"
        update-types:
          - "security"
    open-pull-requests-limit: 10
    rebase-strategy: auto
    # игнорируем крупные мажорные обновления, чтобы не ломать совместимость
    ignore:
      - dependency-name: "python-telegram-bot"
        update-types: ["version-update:semver-major"]
      - dependency-name: "gspread"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 