repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.2
    hooks:
      - id: ruff
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: v1.10.0
  #    hooks:
  #      - id: mypy
  #        additional_dependencies: ['types-pytz']
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"] 