name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest
          # установка самого проекта может падать из-за ещё не настроенного packaging;
          # не прерываем CI
          pip install . || true

      - name: Ruff
        run: ruff check . || true

      - name: Mypy
        run: mypy . || true

      - name: Pytest
        run: pytest || true  # пока тестов нет 