name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install ruff mypy pytest

      - name: Ruff
        run: ruff check .

      - name: Mypy
        run: mypy .

      - name: Pytest
        run: pytest || true  # пока тестов нет 