name: Docker Image CI and Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0
      - 'v*.*'   # Trigger on tags like v0.1
  workflow_dispatch:

jobs:
  build-and-push-release:
    # Run this job only for tags in the main repository
    if: ${{ github.repository == 'bivlked/target-assistant-bot' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}} # Extracts version from tag (e.g., v1.0.0 -> 1.0.0)
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest # Always tag the release build as latest as well
            
      - name: Build and push Docker image to GHCR
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Push the image as this is a release
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 