name: Manual Deploy Documentation to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy documentation from'
        required: false
        default: 'main'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
      
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build/html/
      
      - name: Deploy to GitHub Pages with retries
        uses: actions/deploy-pages@v4
        id: deployment
        continue-on-error: true
      
      # Retry logic
      - name: Wait and retry if failed
        if: steps.deployment.outcome == 'failure'
        run: |
          echo "First deployment attempt failed. Waiting 30 seconds before retry..."
          sleep 30
      
      - name: Retry deployment
        if: steps.deployment.outcome == 'failure'
        uses: actions/deploy-pages@v4 